### PR TITLE
Drop abseil-cpp build workarounds on Windows

### PR DESCRIPTION
**Pull request by stanhu**

### CODE REVIEW

**Comment by stanhu** [comment]
pkgconf doesn't appear to have been updated yet. Closing.

**Comment by mudge** [comment]
Is our only option to wait for GitHub to update the Windows runners?

**Comment by stanhu** [comment]
> Is our only option to wait for GitHub to update the Windows runners? 

We might be able to update `pkgconf` manually.

**Comment by mudge** [comment]
Would it be best to fold this into https://github.com/mudge/re2/pull/95 if that’s a requirement?

**Comment by stanhu** [comment]
> Would it be best to fold this into https://github.com/mudge/re2/pull/95 if that’s a requirement?

Yes. I'm still seeing some failed builds due to `pkgconf`. Filed https://github.com/pkgconf/pkgconf/issues/322.

**Pull request closed without merging**
